openapi: "3.0.0"

info:
  version: 0.0.1
  title: Person Service API

servers:
  - url: https://ryzzrc7lgb.execute-api.us-east-1.amazonaws.com/prod

paths:
  /v1/ping:
    get:
      summary: Checks to see if the API GW and Lambda is up.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  control:
                    type: object
                    properties:
                      ResponseCode:
                        type: number
                      TraceID:
                        type: string
                  data:
                    type: string
                example:
                  control:
                    ResponseCode: 2000
                    TraceID: "f1a8207b-a1e5-4ef4-8425-9ecaa7e1a457"
                  data: "pong"

  /v1/person:
    post:
      summary: Creates a person
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                name:
                  type: string
                email:
                  type: string
              example:
                client_id: "94a72d65-b27e-4a84-be46-1bdc237f7a8f"
                name: "Rehan"
                email: "rehan123456@gmail.com"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  control:
                    type: object
                    properties:
                      ResponseCode:
                        type: number
                      TraceID:
                        type: string
                  data:
                    type: object
                    properties:
                      person_id:
                        type: string
                      client_id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      created_at:
                        type: string
                example:
                  control:
                    ResponseCode: 2000
                    TraceID: "f3a04797-8d56-4604-ad10-933feccf7015"
                  data:
                    person_id: "d3105a92-ae4a-421c-9d69-c12c470061b4"
                    client_id: "94a72d65-b27e-4a84-be46-1bdc237f7a8f"
                    name: "Rehan"
                    email: "rehan123456@gmail.com"
                    created_at: "2020-06-25 17:59:10.961"

  /v1/person/:
    get:
      summary: Finds the first X amount of persons
      parameters:
        - name: limit
          description: The amount of persons to return, max 100
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  control:
                    type: object
                    properties:
                      ResponseCode:
                        type: number
                      TraceID:
                        type: string
                  data:
                    type: object
                    properties:
                      Items:
                        type: array
                        items:
                          type: object
                          properties:
                            person_id:
                              type: string
                            client_id:
                              type: string
                            name:
                              type: string
                            email:
                              type: string
                            created_at:
                              type: string
                example:
                  control:
                    ResponseCode: 2000
                    TraceID: "f3a04797-8d56-4604-ad10-933feccf7015"
                  data:
                    - person_id: "d3105a92-ae4a-421c-9d69-c12c470061b4"
                      client_id: "94a72d65-b27e-4a84-be46-1bdc237f7a8f"
                      name: "Rehan"
                      email: "rehan123456@gmail.com"
                      created_at: "2020-06-25 17:59:10.961"

